with-expecter: true
mock-build-tags: "!compile"
inpackage: true
issue-845-fix: True
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
packages:
  github.com/ksysoev/wsget/pkg/core:
    interfaces:
      Editor:
      CommandFactory:
      Executer:
      ExecutionContext:
      Formater:
      ConnectionHandler:
  github.com/ksysoev/wsget/pkg/core/command:
    interfaces:
      MacroRepo:
  github.com/ksysoev/wsget/pkg/core/edit:
    interfaces:
      HistoryRepo:
  github.com/ksysoev/wsget/pkg/ws:
    interfaces:
      reader:
