with-expecter: true
mock-build-tags: "!compile"
inpackage: true
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/ksysoev/wsget/pkg/core:
    interfaces:
      Editor:
      CommandFactory:
      Executer:
      ExecutionContext:
  github.com/ksysoev/wsget/pkg/edit:
    interfaces:
      HistoryRepo:
